### ISSUE TITLE
Let's say i have connected:

### ISSUE THREAD

**Issue by Ahmed7683** [WalletConnect/EIP6963#58]
Let's say i have connected:

- MetaMask
- Trust Wallet

I want to have some sort of sign message / send transaction buttons. Simple 0.0001 ETH transaction can be good as an example and message signing text can just be "Hello" .

Bonus:
Also this is not urgent, but if you could make sure whenever i connect a wallet and then reload a page i would like to see my wallets in a `connected` state instead of connecting my wallets again.

_Originally posted by @easyrun42 in https://github.com/WalletConnect/EIP6963/issues/44#issuecomment-1783087394_

**Comment by boidushya** [comment]
You can try those over here: https://lab.web3modal.com/library/wagmi/
